<template>
  <Teleport to="body"><div v-if="isOpen" class="cart-backdrop" @mousedown.self="emit('close')"><aside class="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title"><header class="cart-header"><div><p class="eyebrow">Tu seleccion</p><h2 id="cart-title">Carrito</h2></div><button class="icon-button" type="button" aria-label="Cerrar carrito" @click="emit('close')"><X :size="20" /></button></header><div v-if="items.length" class="cart-items"><article v-for="item in items" :key="item.id" class="cart-item"><img v-if="item.imageUrl" :src="item.imageUrl" :alt="item.name" /><div v-else class="image-placeholder" aria-hidden="true"></div><div class="cart-item__content"><strong>{{ item.name }}</strong><span>{{ formatMoney(item.priceCents) }}</span><div class="quantity-control" :aria-label="`Cantidad de ${item.name}`"><button type="button" aria-label="Reducir cantidad" @click="emit('decrease', item.id)"><Minus :size="15" /></button><span>{{ item.quantity }}</span><button type="button" aria-label="Aumentar cantidad" :disabled="item.quantity >= item.stock" @click="emit('increase', item.id)"><Plus :size="15" /></button></div></div><button class="icon-button cart-item__remove" type="button" aria-label="Eliminar producto" @click="emit('remove', item.id)"><Trash2 :size="17" /></button></article></div><div v-else class="cart-empty"><ShoppingBag :size="28" aria-hidden="true" /><p>Tu carrito esta vacio.</p></div><footer v-if="items.length" class="cart-footer"><div><span>Subtotal</span><strong>{{ formatMoney(subtotalCents) }}</strong></div><button class="pay-button cart-checkout" type="button" @click="emit('checkout')">Pagar carrito</button><p>Revisaras los datos de pago antes de confirmar.</p></footer></aside></div></Teleport>
</template>
<script setup lang="ts">
import { Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-vue-next';
import type { CartItem } from '../types/cart';
defineProps<{ isOpen: boolean; items: CartItem[]; subtotalCents: number }>();
const emit = defineEmits<{ close: []; increase: [productId: string]; decrease: [productId: string]; remove: [productId: string]; checkout: [] }>();
const formatMoney = (amount: number): string => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(amount / 100);
</script>
