<template>
  <main class="storefront">
    <header class="storefront-header"><a class="brand" href="#catalog">NORTHSTAR <span>PAY</span></a><div class="header-actions"><div class="secure-note"><ShieldCheck :size="17" aria-hidden="true" /> Compra protegida</div><button class="cart-trigger" :class="{ 'is-bumping': isCartFeedbackVisible }" type="button" :aria-label="`Abrir carrito, ${cartItemCount} productos`" @click="isCartOpen = true"><ShoppingBag :size="19" aria-hidden="true" /><span v-if="cartItemCount">{{ cartItemCount }}</span></button></div></header>
    <section class="catalog-intro" aria-labelledby="catalog-title"><p class="eyebrow">Tecnologia seleccionada</p><h1 id="catalog-title">Elige lo que quieres llevar hoy.</h1><p>Productos pensados para tu dia a dia, con disponibilidad visible y un pago seguro en pocos pasos.</p></section>
    <section v-if="isLoading" class="catalog-status" aria-live="polite">Cargando catalogo...</section>
    <section v-else-if="loadError" class="catalog-status" aria-live="assertive"><p>No fue posible cargar el catalogo.</p><button class="secondary-button" type="button" @click="loadProducts">Reintentar</button></section>
    <template v-else-if="products.length"><section class="catalog-toolbar" aria-label="Informacion del catalogo"><p><strong>{{ products.length }} productos</strong> disponibles para envio nacional</p><span>Revisa el detalle, agrega al carrito o compra directamente</span></section><section id="catalog" class="catalog-layout" aria-label="Catalogo de productos"><section class="product-grid" aria-label="Productos disponibles"><article v-for="item in products" :key="item.id" class="product-card"><button type="button" class="product-card__select" :aria-label="`Ver detalle de ${item.name}`" @click="viewProduct(item)"><img v-if="item.imageUrl" :src="item.imageUrl" :alt="item.name" /><div v-else class="image-placeholder" aria-hidden="true"></div></button><div class="product-card__body"><div class="product-card__meta"><span>{{ item.stock > 0 ? `${item.stock} disponibles` : 'Agotado' }}</span></div><strong>{{ item.name }}</strong><p>{{ item.description }}</p><span class="product-card__price">{{ formatMoney(item.priceCents) }}</span><div class="product-card__actions"><button class="detail-button" type="button" @click="viewProduct(item)"><Eye :size="16" aria-hidden="true" /> Ver detalle</button><button class="cart-add-button" type="button" :disabled="item.stock === 0" @click="addProductToCart(item)"><ShoppingCart :size="16" aria-hidden="true" /><span>Agregar</span></button><button class="pay-button" type="button" :disabled="item.stock === 0" @click="openDirectPurchase(item)">Comprar</button></div></div></article></section></section></template>
    <ProductDetailModal v-if="selectedProduct" :is-open="isDetailOpen" :product="selectedProduct" @close="closeDetails" @add-to-cart="addProductToCart(selectedProduct)" @buy="openDirectPurchase(selectedProduct)" />
    <div v-if="isQuantityOpen && selectedProduct" class="purchase-quantity-backdrop" @mousedown.self="closeDirectPurchase"><section class="purchase-quantity-modal" role="dialog" aria-modal="true" aria-labelledby="purchase-quantity-title"><header><div><p class="eyebrow">Compra directa</p><h2 id="purchase-quantity-title">Elige la cantidad</h2></div><button class="icon-button" type="button" aria-label="Cerrar selector de cantidad" @click="closeDirectPurchase"><X :size="20" /></button></header><div class="purchase-quantity__product"><div><span>{{ selectedProduct.stock }} disponibles</span><strong>{{ selectedProduct.name }}</strong><small>{{ formatMoney(selectedProduct.priceCents) }} por unidad</small></div><strong>{{ formatMoney(selectedProduct.priceCents * directPurchaseQuantity) }}</strong></div><div class="purchase-quantity__control"><span>Cantidad</span><div class="quantity-control"><button type="button" aria-label="Reducir cantidad de compra" :disabled="directPurchaseQuantity === 1" @click="directPurchaseQuantity--"><Minus :size="16" /></button><strong>{{ directPurchaseQuantity }}</strong><button type="button" aria-label="Aumentar cantidad de compra" :disabled="directPurchaseQuantity >= selectedProduct.stock" @click="directPurchaseQuantity++"><Plus :size="16" /></button></div></div><footer><button class="secondary-button" type="button" @click="closeDirectPurchase">Cancelar</button><button class="pay-button purchase-quantity__continue" type="button" @click="continueDirectPurchase">Continuar al pago</button></footer></section></div>        <CartDrawer :is-open="isCartOpen" :items="store.state.cart" :subtotal-cents="cartSubtotalCents" @close="isCartOpen = false" @increase="increaseCartItem" @decrease="decreaseCartItem" @remove="removeFromCart" @checkout="checkoutCart" />
    <Transition name="cart-feedback"><div v-if="isCartFeedbackVisible" class="cart-feedback" role="status"><Check :size="18" aria-hidden="true" /><span><strong>Agregado al carrito</strong><small>{{ addedProductName }}</small></span></div></Transition>        <button v-if="cartItemCount" class="cart-quick-view" type="button" :aria-label="`Ver carrito con ${cartItemCount} productos`" @click="isCartOpen = true"><ShoppingBag :size="20" aria-hidden="true" /><span><strong>{{ cartItemCount }} {{ cartItemCount === 1 ? 'producto' : 'productos' }}</strong><small>{{ formatMoney(cartSubtotalCents) }}</small></span><ArrowRight :size="18" aria-hidden="true" /></button>
    <CheckoutModal v-if="selectedProduct && checkoutItems.length" :product="selectedProduct" :items="checkoutItems" :is-processing="isProcessing" :payment-error="paymentError" :acceptance-documents="acceptanceDocuments" @confirm="handlePayment" />
    <PaymentResultModal v-if="paymentResult" :is-open="store.state.step === 'result'" :status="paymentResult.status" :reference="paymentResult.reference" :status-message="paymentResult.statusMessage" :total-amount-cents="paymentResult.totalAmountCents" @return-to-product="returnToProduct" />
  </main>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { ArrowRight, Check, Eye, Minus, Plus, ShieldCheck, ShoppingBag, ShoppingCart, X } from 'lucide-vue-next';
import { createCheckoutTransaction, getAcceptanceDocuments, type CheckoutTransactionResponse } from '../api/checkout.api';
import { getProducts } from '../api/products.api';
import CartDrawer from '../components/CartDrawer.vue';
import CheckoutModal, { type CheckoutPaymentData } from '../components/checkout/CheckoutModal.vue';
import PaymentResultModal from '../components/checkout/PaymentResultModal.vue';
import ProductDetailModal from '../components/ProductDetailModal.vue';
import { store } from '../store';
import type { Product } from '../types/product';
import type { CartItem } from '../types/cart';
import type { AcceptanceDocuments } from '../types/acceptance-documents';

const products = ref<Product[]>([]); const selectedProduct = ref<Product | null>(null); const addedProductName = ref(''); const isCartFeedbackVisible = ref(false); let cartFeedbackTimer: ReturnType<typeof setTimeout> | undefined; const isQuantityOpen = ref(false); const directPurchaseQuantity = ref(1); const checkoutItems = ref<CartItem[]>([]); const checkoutKey = ref(''); const isCartCheckout = ref(false); const isDetailOpen = ref(false); const isCartOpen = ref(false); const isLoading = ref(true); const loadError = ref(false); const isProcessing = ref(false); const paymentError = ref(''); const paymentResult = ref<CheckoutTransactionResponse | null>(null); const acceptanceDocuments = ref<AcceptanceDocuments | null>(null);
const cartItemCount = computed(() => store.state.cart.reduce((total, item) => total + item.quantity, 0));
const cartSubtotalCents = computed(() => store.state.cart.reduce((total, item) => total + item.priceCents * item.quantity, 0));
const formatMoney = (amount: number): string => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(amount / 100);
const loadProducts = async (): Promise<void> => { isLoading.value = true; loadError.value = false; try { products.value = await getProducts(); selectedProduct.value = null; isDetailOpen.value = false; } catch { loadError.value = true; } finally { isLoading.value = false; } };
const selectProduct = (product: Product): void => { selectedProduct.value = product; };
const viewProduct = (product: Product): void => { selectProduct(product); isDetailOpen.value = true; };
const closeDetails = (): void => { isDetailOpen.value = false; };
const addProductToCart = (product: Product): void => { store.commit('addToCart', product); addedProductName.value = product.name; isCartFeedbackVisible.value = true; if (cartFeedbackTimer) clearTimeout(cartFeedbackTimer); cartFeedbackTimer = setTimeout(() => { isCartFeedbackVisible.value = false; }, 2400); };
const increaseCartItem = (productId: string): void => { store.commit('increaseCartItem', productId); };
const decreaseCartItem = (productId: string): void => { store.commit('decreaseCartItem', productId); };
const removeFromCart = (productId: string): void => { store.commit('removeFromCart', productId); };
const openDirectPurchase = (product: Product): void => { if (product.stock < 1) return; selectProduct(product); directPurchaseQuantity.value = 1; closeDetails(); isQuantityOpen.value = true; };
const closeDirectPurchase = (): void => { isQuantityOpen.value = false; };
const continueDirectPurchase = (): void => { if (!selectedProduct.value || directPurchaseQuantity.value < 1 || directPurchaseQuantity.value > selectedProduct.value.stock) return; isQuantityOpen.value = false; startCheckout([{ ...selectedProduct.value, quantity: directPurchaseQuantity.value }], false); };
const checkoutCart = (): void => { if (!store.state.cart.length) return; startCheckout(store.state.cart.map((item) => ({ ...item })), true); isCartOpen.value = false; };
const handlePayment = async (paymentData: CheckoutPaymentData): Promise<void> => { if (!selectedProduct.value || !checkoutKey.value || isProcessing.value) return; isProcessing.value = true; paymentError.value = ''; try { paymentResult.value = await createCheckoutTransaction(checkoutItems.value, paymentData, checkoutKey.value); if (isCartCheckout.value && paymentResult.value.status === 'APPROVED') store.commit('clearCart'); store.commit('setTransactionResult', paymentResult.value); } catch { paymentError.value = 'No fue posible procesar el pago. Verifica tus datos e intentalo nuevamente.'; } finally { isProcessing.value = false; } };
const returnToProduct = async (): Promise<void> => { paymentResult.value = null; checkoutItems.value = []; checkoutKey.value = ''; isCartCheckout.value = false; store.commit('reset'); await loadProducts(); };
const startCheckout = (items: CartItem[], fromCart: boolean): void => { if (!items.length || items.some((item) => item.stock < item.quantity)) return; selectedProduct.value = items[0]; checkoutItems.value = items; checkoutKey.value = crypto.randomUUID(); isCartCheckout.value = fromCart; closeDetails(); void getAcceptanceDocuments().then((documents) => { acceptanceDocuments.value = documents; }).catch(() => { acceptanceDocuments.value = null; }); store.commit('selectProduct', selectedProduct.value.id); };
onMounted(loadProducts);
onBeforeUnmount(() => { if (cartFeedbackTimer) clearTimeout(cartFeedbackTimer); });
</script>
